springboot 3.1.2 migration (#295)
* wiremock 3 to fix NoClassDefFoundError: javax/servlet/DispatcherType
* springcloud output-bindings migration
* Tests, receive messages from consummed queues, they are now copied with new spring cloud otherwise tests fail because we assert that queues are empty in teardown to ensure that we don't have unknown messages that are beeing sent
Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>
Co-authored-by: HARPER Jon <jon.harper87@gmail.com>