fixup springboot3 migration network-store client 1.4 needed (#333)
network-modification-server_1    | java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.client.ClientHttpResponse.getStatusCode()'
network-modification-server_1    | 	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[na:na]
network-modification-server_1    | 	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source) ~[na:na]
network-modification-server_1    | 	at org.gridsuite.modification.server.service.BuildWorkerService.startBuild(BuildWorkerService.java:116) ~[classes/:na]
network-modification-server_1    | 	at org.gridsuite.modification.server.service.BuildWorkerService.lambda$consumeBuild$1(BuildWorkerService.java:107) ~[classes/:na]
network-modification-server_1    | Caused by: java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.client.ClientHttpResponse.getStatusCode()'
network-modification-server_1    | 	at com.powsybl.network.store.client.RestTemplateResponseErrorHandler.hasError(RestTemplateResponseErrorHandler.java:32) ~[powsybl-network-store-client-1.3.0.jar:na]
network-modification-server_1    | 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:904) ~[spring-web-6.0.11.jar:6.0.11]
network-modification-server_1    | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864) ~[spring-web-6.0.11.jar:6.0.11]
network-modification-server_1    | 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.11.jar:6.0.11]
network-modification-server_1    | 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:675) ~[spring-web-6.0.11.jar:6.0.11]
network-modification-server_1    | 	at com.powsybl.network.store.client.RestClientImpl.getDocument(RestClientImpl.java:46) ~[powsybl-network-store-client-1.3.0.jar:na]
network-modification-server_1    | 	at com.powsybl.network.store.client.RestClientImpl.getOne(RestClientImpl.java:77) ~[powsybl-network-store-client-1.3.0.jar:na]
network-modification-server_1    | 	at com.powsybl.network.store.client.RestNetworkStoreClient.get(RestNetworkStoreClient.java:88) ~[powsybl-network-store-client-1.3.0.jar:na]
network-modification-server_1    | 	at com.powsybl.network.store.client.RestNetworkStoreClient.getNetwork(RestNetworkStoreClient.java:159) ~[powsybl-network-store-client-1.3.0.jar:na]
network-modification-server_1    | 	at com.powsybl.network.store.iidm.impl.AbstractForwardingNetworkStoreClient.getNetwork(AbstractForwardingNetworkStoreClient.java:18) ~[powsybl-network-store-iidm-impl-1.3.0.jar:na]
network-modification-server_1    | 	at com.powsybl.network.store.iidm.impl.CachedNetworkStoreClient.lambda$new$1(CachedNetworkStoreClient.java:29) ~[powsybl-network-store-iidm-impl-1.3.0.jar:na]